In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets/Cab_Fare_Neural_Network.csv")
df.head()

,Trip_ID,Pickup_Area,Drop_Area,Distance_km,Trip_Duration_min,Time_of_Day,Day_of_Week,Traffic_Level,Weather,Peak_Hour,Passenger_Count,Cab_Type,Payment_Mode,Driver_Rating,Fare_INR
0,TRIP00001,Jewel Chowk,Rehari,25.94,54,Morning,Wednesday,Medium,Sunny,Yes,1,Sedan,Card,4.1,545.20
1,TRIP00002,Railway Station,Sainik Colony,2.03,5,Morning,Saturday,Medium,Sunny,Yes,1,Mini,UPI,4.5,190.11
2,TRIP00003,University,Trikuta Nagar,14.13,32,Morning,Monday,Medium,Sunny,Yes,4,Mini,Card,3.7,359.57
3,TRIP00004,University,Sainik Colony,25.12,41,Night,Friday,Low,Cloudy,No,1,Sedan,UPI,4.8,501.94
4,TRIP00005,Bakshi Nagar,Roop Nagar,7.34,25,Afternoon,Saturday,High,Cloudy,No,2,Sedan,Card,4.6,294.13

In [ ]:
df.describe()

,Distance_km,Trip_Duration_min,Passenger_Count,Driver_Rating,Fare_INR
count,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,20.387615,50.173800,2.501300,4.24756,453.525408
std,11.208101,31.878598,1.123443,0.43514,183.422682
min,1.000000,5.000000,1.000000,3.50000,70.000000
25%,10.707500,25.000000,1.000000,3.90000,304.640000
50%,20.210000,45.000000,2.000000,4.20000,446.035000
75%,30.060000,69.000000,4.000000,4.60000,586.912500
max,39.990000,140.000000,4.000000,5.00000,1026.030000

In [ ]:
df.shape

(10000, 15)

In [ ]:
df.info()
df.drop('Trip_ID', axis=1, inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Trip_ID            10000 non-null  object
 1   Pickup_Area        10000 non-null  object
 2   Drop_Area          10000 non-null  object
 3   Distance_km        10000 non-null  float64
 4   Trip_Duration_min  10000 non-null  int64
 5   Time_of_Day        10000 non-null  object
 6   Day_of_Week        10000 non-null  object
 7   Traffic_Level      10000 non-null  object
 8   Weather            10000 non-null  object
 9   Peak_Hour          10000 non-null  object
 10  Passenger_Count    10000 non-null  int64
 11  Cab_Type           10000 non-null  object
 12  Payment_Mode       10000 non-null  object
 13  Driver_Rating      10000 non-null  float64
 14  Fare_INR           10000 non-null  float64
dtypes: float64(3), int64(2), object(10)
memory usage: 1.1+ MB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pickup_Area        10000 non-null  object
 1   Drop_Area          10000 non-null  object
 2   Distance_km        10000 non-null  float64
 3   Trip_Duration_min  10000 non-null  int64
 4   Time_of_Day        10000 non-null  object
 5   Day_of_Week        10000 non-null  object
 6   Traffic_Level      10000 non-null  object
 7   Weather            10000 non-null  object
 8   Peak_Hour          10000 non-null  object
 9   Passenger_Count    10000 non-null  int64
 10  Cab_Type           10000 non-null  object
 11  Payment_Mode       10000 non-null  object
 12  Driver_Rating      10000 non-null  float64
 13  Fare_INR           10000 non-null  float64
dtypes: float64(3), int64(2), object(9)
memory usage: 1.1+ MB

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('Fare_INR', axis=1)
y = df['Fare_INR']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train, X_valid, y_train, y_valid = train_test_split(
    X_train,
    y_train,
    test_size=0.2,
    random_state=42
)

In [ ]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6400 entries, 2579 to 6090
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Pickup_Area        6400 non-null   object
 1   Drop_Area          6400 non-null   object
 2   Distance_km        6400 non-null   float64
 3   Trip_Duration_min  6400 non-null   int64
 4   Time_of_Day        6400 non-null   object
 5   Day_of_Week        6400 non-null   object
 6   Traffic_Level      6400 non-null   object
 7   Weather            6400 non-null   object
 8   Peak_Hour          6400 non-null   object
 9   Passenger_Count    6400 non-null   int64
 10  Cab_Type           6400 non-null   object
 11  Payment_Mode       6400 non-null   object
 12  Driver_Rating      6400 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 700.0+ KB

In [ ]:
# cat_data = X_train.select_dtypes(include = ['object'])
# num_data = X_train.select_dtypes(exclude = ['object'])

In [ ]:
# from sklearn.preprocessing import OneHotEncoder

In [ ]:
# hot_encoder = OneHotEncoder(sparse_output=False, handle_unknown= "ignore")

# cat_X_train = hot_encoder.fit_transform(cat_data)

In [ ]:
# from sklearn.preprocessing import StandardScaler

In [ ]:
# std_scaler = StandardScaler()

# num_X_train = std_scaler.fit_transform(num_data)

In [ ]:
# X_train_processed = np.hstack((num_X_train, cat_X_train)) #now its a numpy array not dataframe

In [ ]:
# print(X_train_processed.shape)
# print(type(X_train_processed))
# print(X_train_processed.dtype)
# print(X_train_processed[:2])

In [ ]:
from sklearn import preprocessing
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

# cat_data = X_train.select_dtypes(include = ['object'])
# num_data = X_train.select_dtypes(exclude = ['object'])

num_cols = X_train.select_dtypes(exclude=["object"]).columns
cat_cols = X_train.select_dtypes(include=["object"]).columns

num_pipeline = make_pipeline(SimpleImputer(strategy = "median"), StandardScaler())
cat_pipeline = make_pipeline(SimpleImputer(strategy = "most_frequent"), OneHotEncoder(sparse_output=False, handle_unknown= "ignore"))

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("cat", cat_pipeline, cat_cols)
])

X_train_processed = preprocessor.fit_transform(X_train)
X_validate_processed = preprocessor.transform(X_valid)
X_test_processed = preprocessor.transform(X_test)

In [ ]:
print(X_train_processed.shape)
print(type(X_train_processed))
print(X_train_processed.dtype)
print(X_train_processed[:2])

(6400, 70)
<class 'numpy.ndarray'>
float64
[[-0.86145294 -0.89260468 -0.44528788 -0.34240398  0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          1.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.          0.          1.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.          0.          1.          0.          0.
   0.          1.          0.          1.          1.          0.
   0.          1.          0.          0.        ]
 [ 1.73696086  2.52279671 -1.33253647 -0.34240398  0.          0.
   0.          0.          1.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   1.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          1.          0.
   1.          0.          0.          0.          0.          0.
   0.          1.          0.          0.          0.          0.
   0.          1.          0.          1.          0.          0.
   1.          0.          0.          1.        ]]

In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
tf.random.set_seed(42)

model = tf.keras.Sequential(
    [
        tf.keras.layers.Input(shape=(X_train_processed.shape[1],)),
        tf.keras.layers.Dense(100, activation="relu"),
        tf.keras.layers.Dense(100, activation="relu"),
        tf.keras.layers.Dense(100, activation="relu"),
        tf.keras.layers.Dense(1)
    ]
)

optimizer = tf.keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="mse", optimizer = optimizer, metrics = ["RootMeanSquaredError"])

history = model.fit(X_train_processed, y_train, epochs=20, validation_data=(X_validate_processed, y_valid))

mse_test, rmse_test = model.evaluate(X_test_processed, y_test)

y_pred = model.predict(X_test_processed)

Epoch 1/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 5s 9ms/step - RootMeanSquaredError: 255.2988 - loss: 65177.5000 - val_RootMeanSquaredError: 43.3993 - val_loss: 1883.4996
Epoch 2/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 35.8974 - loss: 1288.6226 - val_RootMeanSquaredError: 32.2208 - val_loss: 1038.1802
Epoch 3/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 29.2876 - loss: 857.7623 - val_RootMeanSquaredError: 27.5958 - val_loss: 761.5271
Epoch 4/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 25.1187 - loss: 630.9500 - val_RootMeanSquaredError: 23.9100 - val_loss: 571.6858
Epoch 5/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 21.8363 - loss: 476.8242 - val_RootMeanSquaredError: 20.9559 - val_loss: 439.1499
Epoch 6/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 18.7887 - loss: 353.0159 - val_RootMeanSquaredError: 17.6270 - val_loss: 310.7096
Epoch 7/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 15.4450 - loss: 238.5482 - val_RootMeanSquaredError: 14.5515 - val_loss: 211.7471
Epoch 8/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 12.5350 - loss: 157.1266 - val_RootMeanSquaredError: 12.1133 - val_loss: 146.7322
Epoch 9/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 10.7636 - loss: 115.8541 - val_RootMeanSquaredError: 11.3028 - val_loss: 127.7525
Epoch 10/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 10.2034 - loss: 104.1102 - val_RootMeanSquaredError: 11.1254 - val_loss: 123.7741
Epoch 11/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.9269 - loss: 98.5426 - val_RootMeanSquaredError: 11.1225 - val_loss: 123.7090
Epoch 12/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.7597 - loss: 95.2526 - val_RootMeanSquaredError: 11.0823 - val_loss: 122.8167
Epoch 13/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.6352 - loss: 92.8376 - val_RootMeanSquaredError: 10.8892 - val_loss: 118.5758
Epoch 14/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.5229 - loss: 90.6858 - val_RootMeanSquaredError: 10.5507 - val_loss: 111.3178
Epoch 15/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.4251 - loss: 88.8326 - val_RootMeanSquaredError: 10.2870 - val_loss: 105.8232
Epoch 16/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.3537 - loss: 87.4915 - val_RootMeanSquaredError: 10.1563 - val_loss: 103.1502
Epoch 17/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - RootMeanSquaredError: 9.3051 - loss: 86.5851 - val_RootMeanSquaredError: 10.1348 - val_loss: 102.7136
Epoch 18/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - RootMeanSquaredError: 9.2655 - loss: 85.8498 - val_RootMeanSquaredError: 10.1800 - val_loss: 103.6317
Epoch 19/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - RootMeanSquaredError: 9.2384 - loss: 85.3482 - val_RootMeanSquaredError: 10.2675 - val_loss: 105.4214
Epoch 20/20
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - RootMeanSquaredError: 9.2129 - loss: 84.8777 - val_RootMeanSquaredError: 10.3701 - val_loss: 107.5380
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - RootMeanSquaredError: 10.3763 - loss: 107.6673
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step